/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSitemapDotxmlRouteImport } from './routes/docs/sitemap[.]xml'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsApiSearchRouteImport } from './routes/docs/api/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSitemapDotxmlRoute = DocsSitemapDotxmlRouteImport.update({
  id: '/docs/sitemap.xml',
  path: '/docs/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiSearchRoute = DocsApiSearchRouteImport.update({
  id: '/docs/api/search',
  path: '/docs/api/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/sitemap.xml': typeof DocsSitemapDotxmlRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/api/search': typeof DocsApiSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/sitemap.xml': typeof DocsSitemapDotxmlRoute
  '/docs': typeof DocsIndexRoute
  '/docs/api/search': typeof DocsApiSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/sitemap.xml': typeof DocsSitemapDotxmlRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/api/search': typeof DocsApiSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/docs/$' | '/docs/sitemap.xml' | '/docs/' | '/docs/api/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs/$' | '/docs/sitemap.xml' | '/docs' | '/docs/api/search'
  id:
    | '__root__'
    | '/'
    | '/docs/$'
    | '/docs/sitemap.xml'
    | '/docs/'
    | '/docs/api/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsSitemapDotxmlRoute: typeof DocsSitemapDotxmlRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsApiSearchRoute: typeof DocsApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/sitemap.xml': {
      id: '/docs/sitemap.xml'
      path: '/docs/sitemap.xml'
      fullPath: '/docs/sitemap.xml'
      preLoaderRoute: typeof DocsSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/search': {
      id: '/docs/api/search'
      path: '/docs/api/search'
      fullPath: '/docs/api/search'
      preLoaderRoute: typeof DocsApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsSitemapDotxmlRoute: DocsSitemapDotxmlRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsApiSearchRoute: DocsApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
